version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  # AfterInstall:
  #   - location: scripts/load_db.sh
  #     timeout: 30
  #     runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ubuntu