version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/jacobsalway.com
permissions:
  - object: /home/ec2-user/jacobsalway.com
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ubuntu